name: iOS-watchOS-tvOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: xcodebuild build -destination 'name=iPhone 13 Pro Max' -scheme 'BluetoothThing-Package' -derivedDataPath '.build'
