name: macOS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: swift test -v --enable-code-coverage

    - name: Generate code coverage
      run: xcrun llvm-cov export -format="lcov" .build/x86_64-apple-macosx/debug/BluetoothThingPackageTests.xctest/Contents/MacOS/BluetoothThingPackageTests -instr-profile .build/debug/codecov/default.profdata > test.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
