name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage --show-codecov-path
    - name: Generate code coverage
      run: xcrun llvm-cov report .build/x86_64-apple-macosx/debug/BluetoothThingPackageTests.xctest/Contents/MacOS/BluetoothThingPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./.build/x86_64-apple-macosx/debug/codecov/BluetoothThing.json
