name: tvOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: xcodebuild test -destination 'name=Apple TV 4K (2nd generation)' -scheme 'BluetoothThing' -derivedDataPath '.build'
