name: watchOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Resolve Dependencies
      run: swift package resolve

    - name: Build
      run: xcodebuild build -destination 'name=Apple Watch Series 7 - 45mm' -scheme 'BluetoothThing-Package' -derivedDataPath '.build'
